### ISSUE TITLE
What about a tutorial showing how to implement this one

### ISSUE THREAD

**Issue by juarezpaf** [MySiteApp/node-safari-push-notifications#10]
I was reading the documentation related to Safari Push Notifications https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html but it's too much conceptual.

**Comment by kobim** [comment]
Hi @juarezpaf,
This library was created to provide useful functions for dealing with Safari Push Notifications. It wasn't intended to dictate which web server you should use, but to give you a helper functions for implementing your own endpoints.

More specifically, this library produces the signed ZIP file required at registration (the `/v1/pushPackages/WEBSITE_ID` endpoint). The rest of the implementation is up to you...
