### ISSUE TITLE
UserInfo not adding to the request

### ISSUE THREAD

**Issue by yurypaleev** [MySiteApp/node-safari-push-notifications#11]
Why UserInfo not adding to the request?
In logs I see:
`Could not register user for website identifier web.***.***.***, received response 500`

**Comment by kobim** [comment]
Yury, your question is useless without more information.
It looks like when Safari was trying to reach your `/v1/pushPackages` endpoint it encountered a server error (http code 500).
Try debugging that endpoint, and see why it yields this error.
