### ISSUE TITLE
Intermittent Signature Failure 

### ISSUE THREAD

**Issue by msibilsk** [MySiteApp/node-safari-push-notifications#12]
Hi there, 

I am using version 0.3.0.

When using this module I occasionally get the error `Signature verification of push package failed.` from Safari. None of my cert, key, intermediate, or manifest content is changing. I noticed in the signatures that failed there are some garbled/invalid characters. I tried manually taking those characters out and using the signature but it still fails. Do you know anything about this intermittent error and how to prevent it? Is there an updated version of pkcs7 I should be using?

Thank you!

**Comment by kobim** [comment]
Hi @msibilsk ,

Thanks for pointing this out. I took the chance and wrote some tests while trying to reproduce your error, and I encountered the same behavior (failure to verify the signature).
I applied a fix in v0.3.1 (#13) which seems to work (at least in my tests). I would love if you can try the new version (also pushed to npm) and verify everything works.

**Comment by msibilsk** [comment]
Yes, I am no longer getting signature failures. Really appreciate it!
