### ISSUE TITLE
How to get certificates

### ISSUE THREAD

**Issue by arolando** [MySiteApp/node-safari-push-notifications#15]
Hi @kobim, thanks for your package. I'm trying to use it but I can't figure out how to obtain the 3 certificates to pass to the generatePackage method.
Can you point to some tutorial to get them?
Thanks in advance.

**Comment by kobim** [comment]
Hi @arolando,
There's a link to Apple's page in the README - http://apple.co/1rAeIvg . The certificates are generated just like any other certificate from Apple Developers website.

Hope it helps,
Kobi

**Comment by arolando** [comment]
Hi @kobim, I've downloaded the certificate from Apple at: https://developer.apple.com/account/ios/certificate

But I have one certificate. How can I obtain the 3 certificates?
