### ISSUE TITLE
Manifest file creating wrong structure

### ISSUE THREAD

**Issue by raymondflores** [MySiteApp/node-safari-push-notifications#16]
Manifest file creation is returning
`{ "website.json": "hash",
...
}`

Instead it should return 
`{ "website.json":  {
hashType: 'sha512',
hashValue: 'hash'
},
...
}`

I created the fix but im not allowed to push to a branch and therefore cant create a pull request

**Comment by kobim** [comment]
Hi @raymondflores , thanks for letting me know about the [new changes to manifest.json](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW6).

I've seen you already forked this repository, so please push your fixes to your fork and open a pull request (don't forget about tests please) with reference to this issue.
For more information about forking, you can use GitHub's tutorial - https://guides.github.com/activities/forking/

**Comment by raymondflores** [comment]
@kobim I wrote the test coverage for utils which is all i changed. But when i run `npm test` I get this error `SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../../../usr/local/lib/node_modules/jest/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Array.forEach (native)`

**Comment by kobim** [comment]
See jsdom/jsdom#2304 for more details about your error (although the current jest version in the project isn't affected by this problem, so I'm not sure why you are seeing this.)
