### ISSUE TITLE
Cannot deploy into aws beanstalk

### ISSUE THREAD

**Issue by aotol** [MySiteApp/node-safari-push-notifications#24]
I created a NodeJS project and with safari-push-notifications@0.4.0 in my package.json file and dependency.

Cannot deploy into aws beanstalk with package.json during the deployment.

Error message:

"safari-push-notifications": "^0.4.0", 
Response error message:

> safari-push-notifications@0.4.0 install /tmp/deployment/application/node_modules/safari-push-notifications
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.14.158-101.185.amzn1.x86_64
gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v12.14.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v12.14.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/deployment/application/node_modules/safari-push-notifications
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! safari-push-notifications@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the safari-push-notifications@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /tmp/.npm/_logs/2020-02-28T10_16_27_290Z-debug.log
Running npm install: /opt/elasticbeanstalk/node-install/node-v12.14.1-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
UTC 2020/02/28 10:16:27 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log 

Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v12.14.1-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

**Comment by kobim** [comment]
Hi @aotol, this seems more of an elastic beanstalk error rather this package error.
I suggest you try and follow the recommendation on https://github.com/lovell/sharp/issues/373#issuecomment-226849756 and make sure you are not packing your `node_modules` and `build` directories with your deploy package.
There's also a workaround with setting your `HOME` env variable: https://github.com/nodejs/node-gyp/issues/414#issuecomment-193574962
