### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: 

### ISSUE THREAD

**Issue by playground** [MySiteApp/node-safari-push-notifications#3]
This is what I have
  var cert = fs.readFileSync('certificates/cert.pem'),
    key = fs.readFileSync('certificates/key.pem'),
    websiteJson = pushLib.websiteJSON(
      "soConnect", // websiteName
      "web.com.soconnect.notification", // websitePushID
      ["http://soconnect.net"], // allowedDomains
      "http://soconnect.net?id=%@", // urlFormatString
      'a823ca752962ed1504c7c15691dcb276', // authenticationToken (zeroFilled to fit 16 chars)
      'https://localhost' // webServiceURL (Must be https!)
    );
  var zipBuffer = pushLib.generatePackage(
    websiteJson, // The object from before / your own website.json object
    path.join("assets/icons"), // Folder containing the iconset
    cert, // Certificate
    key // Private Key
  );
 fs.writeFileSync("pushPackage.zip", zipBuffer);

======================================
Running OpenSSL 0.9.8zd 8 Jan 2015
I tried switching to OpenSSL 1.0.2a 19 Mar 2015 but didn't make a different.

dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/jefflu/git_repo/sandbox/push-notification/node_modules/safari-push-notifications/build/Release/pkcs7.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/jefflu/git_repo/sandbox/push-notification/node_modules/safari-push-notifications/build/Release/pkcs7.node
  Expected in: dynamic lookup

Thanks.

**Comment by kobim** [comment]
What is your node & npm versions? Which OS X version are you using?
Did you install the library from git or from npm?
Did you have some errors in the `node-gyp` process while compiling the bindings of this module?

**Comment by playground** [comment]
node -v                                                                                                                     
v0.12.2

npm -v
2.10.0

I deleted the node_modules and ran npm install, then the error went away.  

Can this package create manifest.json file for me?

**Comment by kobim** [comment]
Sure.

The `pushPackage.zip` file is the file that should be returned to safari's request for push package. `manifest.json` is signed inside it, could you see it?

**Comment by playground** [comment]
Actually yes, I see the file, I asked the question too soon.
One more question, for some reason, when unzip pushPackage.zip icon_16x16@2x.png and icon_32x32.png always failed to inflate.  I have tried it multiple times make sure those files are not corrupted.  Everything else looks good.  Thanks

**Comment by kobim** [comment]
Verify that your node application have permissions to access the `assets/icons` folder (you can give the directories `a+rx` permissions to check if the problem continues).
If the zip inflates successfully but those two files, it's probably a permissions issue.

Closing due to no real issue.
