### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by mayeaux** [MySiteApp/node-safari-push-notifications#31]
Or is there any other way to send push notifs in nodejs?

**Comment by kobim** [comment]
Hi @mayeaux, this library is still maintained and used. Feel free to try it for yourself.

I am not familiar with other Node.js implementations of this functionality.

**Comment by mayeaux** [comment]
Okay sweet, I will definitely try it out. The only thing that threw me off was this line ` but it seems that OpenSSL's PKCS7 functions weren't available.` , made it seem like maybe the library wasn't able to get working in the end, maybe add a 'but that was solved through ____ and the library is now working'? Just a suggestion, thanks!

**Comment by kobim** [comment]
Thanks for pointing this out!
I refined the description via a35f376. I hope it makes more sense now.
