### ISSUE TITLE
Unsupported engine when upgrading to Node 16

### ISSUE THREAD

**Issue by ruizmarc** [MySiteApp/node-safari-push-notifications#45]
Hi,

After upgrading to node 16, we are getting a warning when installing dependencies: 

```
  npm WARN EBADENGINE Unsupported engine {
  npm WARN EBADENGINE   package: 'safari-push-notifications@0.5.0',
  npm WARN EBADENGINE   required: { node: '>=8.0.0 <13.0.0' },
  npm WARN EBADENGINE   current: { node: 'v16.11.1', npm: '8.0.0' }
  npm WARN EBADENGINE }
```

Is there anything that stops node-safari-push-notifications to adopt npm 8 and node 16?

**Comment by c4b4d4** [comment]
Did you ever figure it out? I'm stuck in this same situation.

**Comment by kobim** [comment]
Should be resolved now for all Node versions below 19 -
https://github.com/MySiteApp/node-safari-push-notifications/blob/1854d0188bded33d58c6e298f84418a592c0dbcf/package.json#L7
