### ISSUE TITLE
node-gyp rebuild failing

### ISSUE THREAD

**Issue by apoorvans** [MySiteApp/node-safari-push-notifications#9]
Guys, first off thanks for this awesome module. This works great on localhost - mac.

On debian 8 though, node 5.10.1, npm 3.8.3, node-gyp 3.3.1 it is failing to build with this error:

> safari-push-notifications@0.3.0 install /data/git/myproject/node_modules/safari-push-notifications
> node-gyp rebuild

make: Entering directory `/data/git/myproject/node_modules/safari-push-notifications/build'
  CXX(target) Release/obj.target/pkcs7/src/openssl.o
  CXX(target) Release/obj.target/pkcs7/src/pkcs7.o
  SOLINK_MODULE(target) Release/obj.target/pkcs7.node
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/pkcs7.node] Error 1
make: Leaving directory `/data/git/myproject/node_modules/safari-push-notifications/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16-0.bpo.3-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/git/myproject/node_modules/safari-push-notifications
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN codemirror-graphql@0.5.1 requires a peer of graphql@^0.6.0 but none was installed.
npm ERR! Linux 3.16-0.bpo.3-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! safari-push-notifications@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the safari-push-notifications@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the safari-push-notifications package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs safari-push-notifications
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls safari-push-notifications
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/git/myproject/npm-debug.log
-----------------
any pointers appreciated.

**Comment by kobim** [comment]
Hi,

It looks like you are missing `libssl-dev`, try to install it and `npm rebuild`.

**Comment by apoorvans** [comment]
@kobim thank a ton, that did it. Closing.
